# Generated by Django 5.0.3 on 2024-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('cpu_count', models.IntegerField()),
                ('cpu_freq', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('total_memory', models.BigIntegerField()),
                ('used_memory', models.BigIntegerField()),
                ('memory_percent', models.FloatField()),
                ('total_disk', models.BigIntegerField()),
                ('used_disk', models.BigIntegerField()),
                ('disk_percent', models.FloatField()),
            ],
        ),
    ]
